name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # 根据你的默认分支名称调整

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 或者你项目使用的 Node 版本
        
    - name: Install and Build
      run: |
        npm ci
        npm run build
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist